name: flutter_lingopod_app
description: "LingoPod 译播客 Flutter 版本"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.0.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  audioplayers: ^5.2.1
  flutter_cache_manager: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - web/