name: lingopod_client
description: "LingoPod 译播客 客户端"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.0.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  audioplayers: ^5.2.1
  flutter_cache_manager: ^3.3.1
  just_audio: ^0.9.36
  just_audio_web: ^0.4.9
  just_audio_windows: ^0.2.0
  just_audio_platform_interface: ^4.2.2
  audio_session: ^0.1.18
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  url_launcher: ^6.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - web/
    - assets/logo.png  # 替换为您的实际文件名

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # 您的logo文件路径