name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output-name: linux
          - os: windows-latest
            output-name: windows

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # 对应 Dart SDK 3.5.4
          channel: 'stable'
          cache: true
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 使用 Eclipse Temurin JDK
          java-version: '17'       # 指定 Java 17 版本

      # Web 构建
      - name: Build Web
        if: matrix.os == 'ubuntu-latest'
        run: |
          flutter config --enable-web
          flutter build web --release
          cd build/web
          zip -r ../../lingopod-web.zip ./*
        
      # Android APK 构建
      - name: Build Android APK
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      # Windows EXE 构建
      - name: Build Windows EXE
        if: matrix.os == 'windows-latest'
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release
          cd build/windows/x64/runner/Release
          7z a -tzip ../../../../../lingopod-windows.zip ./*

      # 确保构建文件被正确打包
      - name: Package Release Files
        run: |
          # 创建发布目录
          mkdir release
          
          # 移动 APK
          cp build/app/outputs/flutter-apk/app-release.apk release/lingopod-android.apk
          
          # 打包 Windows 文件
          Compress-Archive -Path build/windows/runner/Release/* -DestinationPath release/lingopod-windows.zip
          
          # 打包 Web 文件
          Compress-Archive -Path build/web/* -DestinationPath release/lingopod-web.zip

      # 创建 GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/lingopod-android.apk
            release/lingopod-windows.zip
            release/lingopod-web.zip
          name: Release v1.0.0
          draft: false
          prerelease: false
          body: |
            ## 下载
            - [Windows 客户端](https://github.com/${{ github.repository }}/releases/download/v1.0.0/lingopod-windows.zip)
            - [Android APK](https://github.com/${{ github.repository }}/releases/download/v1.0.0/lingopod-android.apk)
            - [Web 版本](https://github.com/${{ github.repository }}/releases/download/v1.0.0/lingopod-web.zip)
            
            ## 部署说明
            ### Web 版本部署
            1. 解压 lingopod-web.zip 到 Web 服务器目录
            2. 配置服务器地址
            
            ### 桌面端
            1. 解压 Windows 压缩包
            2. 运行可执行文件
            3. 在设置中配置服务器地址
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}