name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # 对应 Dart SDK 3.5.4
          channel: 'stable'
          cache: true
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 使用 Eclipse Temurin JDK
          java-version: '17'       # 指定 Java 17 版本

      # 安装 Windows 构建依赖
      - name: Install Windows build dependencies
        run: flutter config --enable-windows-desktop

      # 构建 APK
      - name: Build Android APK
        run: flutter build apk --release
      
      # 构建 Windows
      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release
      
      # 构建 Web
      - name: Build Web
        run: flutter build web --release
      
      # 打包发布文件
      - name: Package Release Files
        run: |
          # 创建发布目录
          New-Item -ItemType Directory -Force -Path release
          
          # 移动 APK
          Copy-Item "build/app/outputs/flutter-apk/app-release.apk" -Destination "release/lingopod-android.apk"
          
          # 检查并打包 Windows 文件（添加错误处理）
          if (Test-Path "build/windows/runner/Release") {
              Compress-Archive -Path "build/windows/runner/Release/*" -DestinationPath "release/lingopod-windows.zip" -Force
          } else {
              Write-Host "Windows build directory not found. Checking current directory structure:"
              Get-ChildItem -Path "build" -Recurse | Select-Object FullName
              exit 1
          }
          
          # 检查并打包 Web 文件（添加错误处理）
          if (Test-Path "build/web") {
              Compress-Archive -Path "build/web/*" -DestinationPath "release/lingopod-web.zip" -Force
          } else {
              Write-Host "Web build directory not found"
              exit 1
          }
          
          # 显示最终的发布目录内容
          Write-Host "Release directory contents:"
          Get-ChildItem -Path "release"

      # 创建 GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/lingopod-android.apk
            release/lingopod-windows.zip
            release/lingopod-web.zip
          name: Release v1.0.0
          draft: false
          prerelease: false
          body: |
            ## 下载
            - [Windows 客户端](https://github.com/${{ github.repository }}/releases/download/v1.0.0/lingopod-windows.zip)
            - [Android APK](https://github.com/${{ github.repository }}/releases/download/v1.0.0/lingopod-android.apk)
            - [Web 版本](https://github.com/${{ github.repository }}/releases/download/v1.0.0/lingopod-web.zip)
            
            ## 部署说明
            ### Web 版本部署
            1. 解压 lingopod-web.zip 到 Web 服务器目录
            2. 配置服务器地址
            
            ### 桌面端
            1. 解压 Windows 压缩包
            2. 运行可执行文件
            3. 在设置中配置服务器地址
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}