name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output-name: linux
          - os: windows-latest
            output-name: windows

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # 对应 Dart SDK 3.5.4
          channel: 'stable'
          cache: true
      
      - name: Install Dependencies
        run: flutter pub get

      # Web 构建
      - name: Build Web
        if: matrix.os == 'ubuntu-latest'
        run: |
          flutter config --enable-web
          flutter build web --release
          cd build/web
          zip -r ../../lingopod-web.zip ./*
        
      # Android APK 构建
      - name: Build Android APK
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      # Windows EXE 构建
      - name: Build Windows EXE
        if: matrix.os == 'windows-latest'
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release
          cd build/windows/x64/runner/Release
          7z a -tzip ../../../../../lingopod-windows.zip ./*

      # 创建 Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            lingopod-windows.zip
            lingopod-web.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## 下载
            - [Windows 客户端](lingopod-windows.zip)
            - [Android APK](app-release.apk)
            - [Web 版本](lingopod-web.zip)
            
            ## 部署说明
            ### Web 版本部署
            1. 解压 lingopod-web.zip 到 Web 服务器目录
            2. 配置服务器地址
            
            ### 桌面端
            1. 解压 Windows 压缩包
            2. 运行可执行文件
            3. 在设置中配置服务器地址
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}