name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # 提前设置签名配置
      - name: Setup Android Keystore
        run: |
          Write-Host "开始配置 Android 签名..."
          
          # 创建 keystore 目录
          New-Item -ItemType Directory -Force -Path keystore
          
          # 将 base64 转换回 jks 文件
          $env:KEYSTORE_BASE64 | Out-File -FilePath keystore/keystore_base64.txt
          certutil -decode keystore/keystore_base64.txt keystore/upload-keystore.jks
          
          # 验证 keystore 文件
          if (Test-Path keystore/upload-keystore.jks) {
              Write-Host "✅ Keystore 文件创建成功"
          } else {
              Write-Host "❌ Keystore 文件创建失败"
              exit 1
          }
          
          # 创建 key.properties 文件
          @"
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=../keystore/upload-keystore.jks
          "@ | Out-File -FilePath android/key.properties -Encoding UTF8
          
          # 验证 key.properties 文件
          if (Test-Path android/key.properties) {
              Write-Host "✅ key.properties 文件创建成功"
              Get-Content android/key.properties | ForEach-Object {
                  if ($_ -match "password") {
                      Write-Host "密码已设置 ****"
                  } else {
                      Write-Host $_
                  }
              }
          } else {
              Write-Host "❌ key.properties 文件创建失败"
              exit 1
          }
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'
          cache: true
      
      - name: Setup Gradle Properties
        run: |
          Copy-Item android/gradle.properties.template android/gradle.properties
          Get-Content android/gradle.properties
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 安装 Windows 构建依赖
      - name: Install Windows build dependencies
        run: flutter config --enable-windows-desktop

      # 首先构建 Windows
      - name: Build Windows
        run: |
          Write-Host "开始 Windows 构建..."
          flutter config --enable-windows-desktop
          flutter create --platforms=windows .
          flutter build windows --release
          
          # 验证 Windows 构建
          Write-Host "检查 Windows 构建输出..."
          $windowsPaths = @(
              "build/windows/x64/x64/Release",
              "build/windows/runner/Release",
              "build/windows/x64/runner/Release"
          )
          
          $buildFound = $false
          foreach ($path in $windowsPaths) {
              if (Test-Path $path) {
                  Write-Host "✅ Windows 构建成功: $path"
                  Write-Host "文件列表:"
                  Get-ChildItem -Path $path -Recurse
                  $buildFound = $true
                  break
              }
          }
          
          if (-not $buildFound) {
              Write-Host "❌ Windows 构建失败，未找到构建目录"
              Write-Host "当前 build/windows 目录结构："
              Get-ChildItem -Path "build/windows" -Recurse
              exit 1
          }
      
      # 然后构建 Web（因为通常比较快）
      - name: Build Web
        run: |
          Write-Host "开始 Web 构建..."
          flutter build web --release
          
          # 验证 Web 构建
          $webPath = "build/web"
          if (Test-Path $webPath) {
              Write-Host "✅ Web 构建成功"
              Write-Host "Web 构建文件列表:"
              Get-ChildItem -Path $webPath -Recurse
          } else {
              Write-Host "❌ Web 构建失败，目录不存在"
              exit 1
          }
      
      # 最后构建 APK（因为最耗时）
      - name: Build Android APK
        run: |
          Write-Host "开始 APK 构建..."
          flutter build apk --release
          
          # 验证 APK 构建
          $apkPath = "build/app/outputs/flutter-apk/app-release.apk"
          if (Test-Path $apkPath) {
              Write-Host "✅ APK 构建成功: $apkPath"
              Write-Host "APK 大小: $((Get-Item $apkPath).length / 1MB) MB"
          } else {
              Write-Host "❌ APK 构建失败，文件不存在"
              exit 1
          }
      
      # 打包发布文件
      - name: Package Release Files
        run: |
          Write-Host "开始打包发布文件..."
          
          # 创建发布目录
          New-Item -ItemType Directory -Force -Path release
          Write-Host "创建发布目录: release"
          
          # 打包 APK（移到最前面）
          Write-Host "`n正在处理 APK..."
          $apkPath = "build/app/outputs/flutter-apk/app-release.apk"
          Write-Host "检查 APK 路径: $apkPath"
          if (Test-Path $apkPath) {
              Write-Host "找到 APK 文件"
              Copy-Item $apkPath -Destination "release/lingopod-android.apk" -Force
              if (Test-Path "release/lingopod-android.apk") {
                  $apkSize = (Get-Item "release/lingopod-android.apk").Length / 1MB
                  Write-Host "✅ APK 复制成功，大小: $apkSize MB"
              } else {
                  Write-Host "❌ APK 复制失败"
                  exit 1
              }
          } else {
              Write-Host "❌ APK 文件未找到，检查构建目录..."
              Write-Host "APK 输出目录内容："
              Get-ChildItem -Path "build/app/outputs/flutter-apk" -ErrorAction SilentlyContinue
              exit 1
          }
          
          # Windows 打包（保持不变）
          Write-Host "`n正在处理 Windows 文件..."
          $windowsBuildPath = "build/windows/x64/runner/Release"
          if (Test-Path $windowsBuildPath) {
              $tempDir = "temp_windows"
              New-Item -ItemType Directory -Force -Path $tempDir
              Copy-Item "$windowsBuildPath/*" -Destination $tempDir -Recurse
              Compress-Archive -Path "$tempDir/*" -DestinationPath "release/lingopod-windows.zip" -Force
              Remove-Item -Path $tempDir -Recurse -Force
              Write-Host "✅ Windows 文件打包完成"
          }
          
          # Web 打包（保持不变）
          Write-Host "`n正在处理 Web 文件..."
          if (Test-Path "build/web") {
              Compress-Archive -Path "build/web/*" -DestinationPath "release/lingopod-web.zip" -Force
              Write-Host "✅ Web 文件打包完成"
          }
          
          # 显示最终结果
          Write-Host "`n发布目录最终内容:"
          Get-ChildItem -Path "release" | ForEach-Object {
              $size = $_.Length / 1MB
              Write-Host "- $($_.Name): $size MB"
          }

      # 创建 GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/lingopod-android.apk
            release/lingopod-windows.zip
            release/lingopod-web.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## 下载
            - [Windows 客户端](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lingopod-windows.zip)
            - [Android APK](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lingopod-android.apk)
            - [Web 版本](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/lingopod-web.zip)
            
            ## 部署说明
            ### Web 版本部署
            1. 解压 lingopod-web.zip 到 Web 服务器目录
            2. 配置服务器地址
            
            ### 桌面端
            1. 解压 Windows 压缩包
            2. 运行可执行文件
            3. 在设置中配置服务器地址
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}